"""
Django settings for management project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import datetime
import json
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ENV_FILE = os.path.join(BASE_DIR, 'env.json')
try:
    file = open(ENV_FILE, 'r')
    env_data = json.load(file)
except:
    env_data = {}


LOGSDB_NAME = os.getenv('logsdb_name', env_data.get('logsdb_name'))
LOGSDB_USER = os.getenv('logsdb_user', env_data.get('logsdb_user'))
LOGSDB_PASSWORD = os.getenv('logsdb_password', env_data.get('logsdb_password'))
LOGSDB_HOST = os.getenv('logsdb_host', env_data.get('logsdb_host'))
LOGSDB_PORT = os.getenv('logsdb_port', env_data.get('logsdb_port'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zyreqxad$p3dyn3^4305f&tn9eli74)g#7^8e4!8uxfru_cbg('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
DEV_HOST = env_data.get('DEVELOMENT_HOST')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'members',
    'rest_framework',
    'rest_framework.authtoken',
    'chat',
    'channels',
    'abdm',
    'activity_log'
]
# for web socket support
ASGI_APPLICATION = 'management.asgi.application'

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT', env_data.get('REDIS_PORT'))
CHANNEL_LAYERS = {
    'default':{
        'BACKEND':'channels_redis.core.RedisChannelLayer' ,
        'CONFIG':{
            "hosts":[(REDIS_HOST, REDIS_PORT)]
        }
    }
}

AUTH_USER_MODEL = 'members.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'activity_log.middleware.ActivityLogMiddleware',
]

ROOT_URLCONF = 'management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASE_ROUTERS = ['activity_log.router.DatabaseAppsRouter']
DATABASE_APPS_MAPPING = {'activity_log': 'logs'}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', env_data.get('DB_NAME')),
        'USER':os.getenv('DN_USER', env_data.get('DB_USER')),
        'PASSWORD':os.getenv('DB_PASSWORD', env_data.get('DB_PASSWORD')),
        'HOST':os.getenv('DB_HOST', env_data.get('DB_HOST')),
        'PORT': os.getenv('DB_PORT', env_data.get('DB_PORT')),
    },
    'logs': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': LOGSDB_NAME,
        'USER': LOGSDB_USER,
        'PASSWORD': LOGSDB_PASSWORD,
        'HOST': LOGSDB_HOST,
        'PORT': LOGSDB_PORT
    }
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'cleaning_management',
#         'USER':'postgres',
#         'PASSWORD':'postgres',
#         'HOST':'host.docker.internal', #db
#         'PORT':5432
#     }
}

ACTIVITYLOG_AUTOCREATE_DB = False
ACTIVITYLOG_ANONYMOUS = True
ACTIVITYLOG_LAST_ACTIVITY = True
ACTIVITYLOG_METHODS = ('POST', 'GET', 'PUT', 'DELETE')
ACTIVITYLOG_EXCLUDE_URLS = ('/admin/activity_log/activitylog', '/')
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication', # restframework-jwt
    ),
}
JWT_AUTH = {
    'JWT_ENCODE_HANDLER':'members.jwt.custom_jwt_encode_handler',

    'JWT_DECODE_HANDLER':'members.jwt.custom_decode_handler',

    'JWT_PAYLOAD_HANDLER':'members.jwt.custom_payload_handler',

    'JWT_PAYLOAD_GET_USERNAME_HANDLER':'members.jwt.get_user_id_from_payload_handler',

    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_ALGORITHM': env_data.get('JWT_ALGORITHM'),
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=300),
    'JWT_ALLOW_REFRESH': False,
    'JWT_AUTH_HEADER_PREFIX': env_data['JWT_AUTH_HEADER_PREFIX'],
}

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

logger = LoggingIntegration(
        level=None,
        event_level='ERROR'
    )

# filter transactions that send to sentry
def sampler_func(sampling_context):
    if isinstance(sampling_context, dict):
        for key, value in sampling_context.items():
            print(f'{key}:{value}')
    else:
        print("context ---> ",sampling_context)
    return 1

SENTRY_EXC = os.path.join(BASE_DIR, 'sentry.json')
 
# add transaction data to a file before send to sentry
def before_send(event, hint):
    f = open(SENTRY_EXC, 'r')
    exc_list = json.load(f)
    try:
        trace_id = event['contexts']['trace']['trace_id']
        exc_list.append({trace_id:event})
        f = open(SENTRY_EXC, 'w')
        exc_list = json.dump(exc_list, f, indent=4)
        f.close()
    except Exception as e:
        print(f'error----{str(e)}')
        pass
    return event

SENTRY_DSN = env_data.get('SENTRY_DSN')
# sentry_sdk.init(
#     dsn= None, #SENTRY_DSN,
#     integrations=[DjangoIntegration()],
#     # traces_sampler=sampler_func,
#     traces_sample_rate=1.0,
#     send_default_pii=True,
#     environment='development',
#     profile_lifecycle='trace',
#     profiles_sample_rate=1,
#     # before_send=before_send
#     # max_breadcrumbs=200,
#     # release='cm-v1' # current version of the app,
#     # debug=True, # for debug level logging y sentry itself,
#     # ignore_errors=[ZeroDivisionError],
# )
