# Generated by Django 3.0.6 on 2025-05-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('sender_id', models.CharField(max_length=10)),
                ('receiver_id', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('sender_id', 'receiver_id')},
            },
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender_id', models.CharField(max_length=10)),
                ('reciever_id', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chat.rooms')),
            ],
        ),
    ]
