# Generated by Django 3.0.6 on 2025-04-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonalprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userpersonalprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userpersonalprofile',
            name='username',
        ),
    ]
