# Generated by Django 3.0.6 on 2025-04-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20250410_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/'),
        ),
    ]
