# Generated by Django 3.0.6 on 2025-04-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20250410_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mail_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
