# Generated by Django 3.0.6 on 2025-04-11 04:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20250410_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iumasterprofile',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
