# Generated by Django 3.0.6 on 2025-04-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20250411_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iumasterprofile',
            name='iu_master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Iudetails', to='members.IuMaster'),
        ),
    ]
