# Generated by Django 3.0.6 on 2025-04-11 06:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20250411_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockmaster',
            name='iu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.IuMaster'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='iu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.IuMaster'),
        ),
        migrations.AlterField(
            model_name='floormaster',
            name='iu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.IuMaster'),
        ),
        migrations.AlterField(
            model_name='rolemapping',
            name='iu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.IuMaster'),
        ),
        migrations.AlterField(
            model_name='roommaster',
            name='iu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.IuMaster'),
        ),
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='profile_picture',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='workschedules',
            name='iu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.IuMaster'),
        ),
    ]
