# Generated by Django 3.0.6 on 2025-04-11 07:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20250411_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
