# Generated by Django 3.0.6 on 2025-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20250411_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='iumaster',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='iumasterprofile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='rolemapping',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='userpersonalprofile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedules',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
