# Generated by Django 3.0.6 on 2025-04-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20250411_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
