# Generated by Django 3.0.6 on 2025-04-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20250417_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
