# Generated by Django 3.0.6 on 2025-04-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floormaster',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='members.BlockMaster'),
        ),
        migrations.AlterField(
            model_name='roommaster',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='members.FloorMaster'),
        ),
        migrations.AlterField(
            model_name='workschedules',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='members.RoomMaster'),
        ),
    ]
