# Generated by Django 3.0.6 on 2025-04-22 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20250422_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_personal', to=settings.AUTH_USER_MODEL),
        ),
    ]
