# Generated by Django 3.0.6 on 2025-04-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20250422_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floormaster',
            name='floor_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
