# Generated by Django 3.0.6 on 2025-08-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
